package:
  name: dasel
  version: 3.3.1
  epoch: 1
  description: "Query and modify data structures from the command line"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - go
      - git
      - patch

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/TomWright/dasel
      tag: v3.3.1
      expected-commit: fba653c7f248aff10f2b89fca93929b64707dfc8

  - uses: patch
    with:
      patches: patches/CVE-2026-33320.patch

  - runs: |
      go build -o "${{targets.destdir}}/usr/bin/dasel" ./cmd/dasel

test:
  pipeline:
    - runs: |
        dasel --version
        echo '{"name":"hagai"}' | dasel -r json '.name'